---
- hosts: all
  become: true 
  vars_files:
   - "./cluster.yml"

  tasks: 
   - name: Install packages that allow apt to be used over HTTPS
     apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes 
     vars:
      packages:
       - apt-transport-https
       - ca-certificates
       - curl
       - vim
       - net-tools
       - software-properties-common

   - name: Remove swapfile from /etc/fstab 
     mount: 
      name: "{{ item }}"
      fstype: swap
      state: absent 
     with_items:
      - swap
      - none 

   - name: Disable swap
     command: swapoff -a 
     when: ansible_swaptotal_mb > 0

   - name: Add an apt signing key for K8s
     apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  
   - name: Adding apt repository for K8s 
     apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

   - name: Install k8s kubelet, kubeadm and kubectl
     apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
     vars: 
      packages:
       - kubelet
       - kubeadm
       - kubectl 

   - name: Configure node IP
     copy:
      content: "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint='unix:///var/run.crio/crio.sock'"
      dest: /etc/default/kubelet
      force: no 
      group: sys
      owner: root 
      mode: 0555

   # Prequisite to install Crio
   - name: IPV4 config 
     shell: |
      modprobe overlay
      modprobe br_netfilter
      cat > /etc/sysctl.d/99-kubernetes-cri.conf <<EOF
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF 
      sysctl --system

   - name: Install Crio Runtime and start 
     shell: |
      . /etc/os-release
      sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
      wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O- | sudo apt-key add -
      sudo apt-get update
  
   - name: Install CRIO 1.17
     apt:
      name: cri-o-1.17
      state: present
      update_cache: yes

   - name: Reload system
     systemd:
      daemon_reload: yes

   - name: Reload system
     systemd:
      name: crio
      state: started
      enabled: yes

   # Copy join command to node 
   - name: Copy join command to node
     copy: src=join-command dest=/tmp/join-command.sh mode=0777

   - name: Join the node to cluster
     command: sh /tmp/join-command.sh 


   